name: Sync on DOM Cloud
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
          data: >-
            {"commands":["echo
            \"NEXT_PUBLIC_SITE_URL=\\\"https://${DOMAIN}\\\"\" >>
            .env","NPM=`which yarn`","$NPM install","$NPM run
            build"],"features":["node
            lts"],"nginx":{"root":"public_html/public","passenger":{"enabled":"on","app_env":"production","app_start_command":"env
            PORT=$PORT yarn
            start"},"locations":[{"match":"/_next/static/","alias":"public_html/.next/static/"}]}}
